### ISSUE TITLE
Implement the logger solution for no actor classes

### ISSUE THREAD

**Issue by takabayashi** [marvin-ai/marvin-engine-executor#32]

**Comment by oldfly** [comment]
work in progress

**Comment by oldfly** [comment]
hi @takabayashi , i found "grizzled-slf4j" at build.sbt file, so i used this library directly for logger implementation.

The log conf file "log4j.properties" is added to /src/main/resources/ , and no actor classes can extend "Logging" to use logger system. 

No actor classes can also instantiate logger system using code below without extending Logging:
val logger = Logger(classOf[JsonUtil.scala])
    logger.info("log message!")

**Comment by takabayashi** [comment]
Done
